# Generated by Django 5.0.1 on 2024-01-13 17:20
import os
import re
from django.db import migrations
from pathlib import Path


def load_cities(apps, schema_editor):
    City = apps.get_model("weather", "City")
    pattern = r"([\w\- ]+).*?([\d.]+).*?([\d.]+)"
    lines = (line for line in open(os.path.join(Path(__file__).resolve().parent.parent, "data", "cities coordinates"),
                                   "r",
                                   encoding='utf-8'))
    for line in lines:
        m = re.match(pattern, line)
        if m:
            city_name = m.group(1).strip()
            formatted_name = city_name.lower().replace("-", " ")
            city = City(name=city_name, formatted_name=formatted_name, latitude=m.group(2), longitude=m.group(3))
            city.save()


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_cities),
    ]
