# Generated by Django 5.0.1 on 2024-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20240113_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pressure_mm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='upd_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
